"""Data access for defect records - pipeline stage 6.

Every query the dashboard needs lives here, so the API routers stay thin and
the storage layer can be swapped (Firestore, Postgres+PostGIS) by
reimplementing this one class.

The store has the two purposes the scope names:
1. feeding the live dashboard (:meth:`list_defects`, :meth:`analytics`,
   :meth:`heatmap`);
2. accumulating reviewed detections as a retraining corpus
   (:meth:`export_for_retraining`).
"""

from __future__ import annotations

import math
import uuid
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from typing import Any, Iterable

from motor.motor_asyncio import AsyncIOMotorDatabase

from app.db.mongo import DEFECTS, JOBS

#: Legal forward transitions, mirroring crackcatch_model.types.STATUS_TRANSITIONS.
STATUS_TRANSITIONS: dict[str, tuple[str, ...]] = {
    "New": ("Verified", "Rejected"),
    "Verified": ("Scheduled", "Rejected"),
    "Scheduled": ("Repaired", "Verified"),
    "Repaired": ("Scheduled",),
    "Rejected": ("New",),
}

OPEN_STATUSES = ("New", "Verified", "Scheduled")


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def priority_band(score: float) -> str:
    if score >= 75.0:
        return "Critical"
    if score >= 55.0:
        return "High"
    if score >= 35.0:
        return "Medium"
    return "Low"


def _as_aware(value: Any) -> Any:
    """MongoDB returns naive UTC datetimes; the API contract is tz-aware."""
    if isinstance(value, datetime) and value.tzinfo is None:
        return value.replace(tzinfo=timezone.utc)
    return value


def serialise(document: dict[str, Any]) -> dict[str, Any]:
    """Convert a raw Mongo document into the API's ``Defect`` shape."""
    doc = dict(document)
    doc["_id"] = str(doc.get("_id", ""))
    for key in ("detected_at", "created_at", "updated_at", "repaired_at"):
        if key in doc:
            doc[key] = _as_aware(doc[key])
    for event in doc.get("history", []) or []:
        if isinstance(event, dict) and "at" in event:
            event["at"] = _as_aware(event["at"])
    doc.pop("location_geo", None)  # internal index field, not part of the API
    doc.setdefault("priority_band", priority_band(doc.get("priority_score", 0.0)))
    return doc


class DefectRepository:
    """All defect persistence and querying."""

    def __init__(self, db: AsyncIOMotorDatabase) -> None:
        self.db = db
        self.collection = db[DEFECTS]
        self.jobs = db[JOBS]

    # ------------------------------------------------------------- writing

    async def create(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Insert one defect, or return the existing row on a repeat client_id.

        ``client_id`` is generated by the pipeline and makes ingestion
        idempotent: re-running the same clip will not duplicate rows.
        """
        now = _utc_now()
        document = dict(payload)

        # `client_id` backs a UNIQUE SPARSE index. A sparse index skips
        # documents where the field is ABSENT, but an explicit null is still
        # indexed - so two rows carrying `client_id: None` collide with a
        # DuplicateKeyError. Callers that omit it (or pass None, which pydantic
        # models do by default) get one generated here, at the single choke
        # point, so a null can never reach the collection.
        if not document.get("client_id"):
            document["client_id"] = uuid.uuid4().hex
        client_id = document["client_id"]

        if client_id:
            existing = await self.collection.find_one({"client_id": client_id})
            if existing:
                return serialise(existing)

        document.setdefault("status", "New")
        document["created_at"] = now
        document["updated_at"] = now
        document["priority_band"] = priority_band(document.get("priority_score", 0.0))
        document["history"] = [
            {
                "status": document["status"],
                "at": now,
                "by": "pipeline",
                "note": "Detected by the CrackCatch pipeline",
            }
        ]

        location = document.get("location") or {}
        if "latitude" in location and "longitude" in location:
            document["location_geo"] = {
                "type": "Point",
                "coordinates": [location["longitude"], location["latitude"]],
            }

        result = await self.collection.insert_one(document)
        document["_id"] = result.inserted_id
        return serialise(document)

    async def create_many(self, payloads: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
        return [await self.create(p) for p in payloads]

    async def update_status(
        self,
        defect_id: str,
        new_status: str | None,
        note: str = "",
        by: str = "authority",
        road_type: str | None = None,
        review_label: str | None = None,
        severity: str | None = None,
    ) -> dict[str, Any] | None:
        """Apply an authority action, enforcing the workflow's transitions."""
        current = await self.get(defect_id)
        if current is None:
            return None

        now = _utc_now()
        updates: dict[str, Any] = {"updated_at": now}
        history_entry: dict[str, Any] | None = None

        if new_status is not None and new_status != current["status"]:
            allowed = STATUS_TRANSITIONS.get(current["status"], ())
            if new_status not in allowed:
                raise ValueError(
                    f"Illegal transition {current['status']} -> {new_status}. "
                    f"Allowed from {current['status']}: {', '.join(allowed) or 'none'}."
                )
            updates["status"] = new_status
            if new_status == "Repaired":
                updates["repaired_at"] = now
            history_entry = {
                "status": new_status,
                "at": now,
                "by": by,
                "note": note,
            }

        if road_type is not None:
            updates["road_type"] = road_type
        if review_label is not None:
            # An authority correcting the class is the strongest retraining
            # signal we get - stage 8 keys off this field.
            updates["review_label"] = review_label
        if note:
            updates["review_note"] = note
        if severity is not None:
            updates["severity"] = severity
            updates["priority_band"] = priority_band(current.get("priority_score", 0.0))

        operation: dict[str, Any] = {"$set": updates}
        if history_entry:
            operation["$push"] = {"history": history_entry}

        await self.collection.update_one({"_id": _oid(defect_id)}, operation)
        return await self.get(defect_id)

    async def attach_repair_photo(self, defect_id: str, path: str) -> dict[str, Any] | None:
        """Before/after verification: attach the post-repair photo."""
        result = await self.collection.update_one(
            {"_id": _oid(defect_id)},
            {"$set": {"repair_photo_path": path, "updated_at": _utc_now()}},
        )
        if result.matched_count == 0:
            return None
        return await self.get(defect_id)

    async def delete(self, defect_id: str) -> bool:
        result = await self.collection.delete_one({"_id": _oid(defect_id)})
        return result.deleted_count > 0

    # ------------------------------------------------------------- reading

    async def get(self, defect_id: str) -> dict[str, Any] | None:
        document = await self.collection.find_one({"_id": _oid(defect_id)})
        return serialise(document) if document else None

    @staticmethod
    def build_filter(
        severity: list[str] | None = None,
        status: list[str] | None = None,
        defect_class: list[str] | None = None,
        date_from: datetime | None = None,
        date_to: datetime | None = None,
        min_priority: float | None = None,
        source_type: str | None = None,
        bbox: tuple[float, float, float, float] | None = None,
        search: str | None = None,
    ) -> dict[str, Any]:
        """Translate dashboard filter controls into a Mongo query."""
        query: dict[str, Any] = {}
        if severity:
            query["severity"] = {"$in": list(severity)}
        if status:
            query["status"] = {"$in": list(status)}
        if defect_class:
            query["defect_class"] = {"$in": list(defect_class)}
        if source_type:
            query["source_type"] = source_type
        if min_priority is not None:
            query["priority_score"] = {"$gte": min_priority}
        if date_from or date_to:
            window: dict[str, Any] = {}
            if date_from:
                window["$gte"] = date_from
            if date_to:
                window["$lte"] = date_to
            query["detected_at"] = window
        if bbox:
            # (min_lon, min_lat, max_lon, max_lat) - the map viewport.
            min_lon, min_lat, max_lon, max_lat = bbox
            query["location.latitude"] = {"$gte": min_lat, "$lte": max_lat}
            query["location.longitude"] = {"$gte": min_lon, "$lte": max_lon}
        if search:
            query["$or"] = [
                {"source_ref": {"$regex": search, "$options": "i"}},
                {"notes": {"$regex": search, "$options": "i"}},
                {"road_type": {"$regex": search, "$options": "i"}},
            ]
        return query

    async def list_defects(
        self,
        query: dict[str, Any] | None = None,
        page: int = 1,
        page_size: int = 50,
        sort_by: str = "detected_at",
        sort_dir: int = -1,
    ) -> tuple[list[dict[str, Any]], int]:
        query = query or {}
        page = max(1, page)
        page_size = max(1, min(page_size, 500))
        total = await self.collection.count_documents(query)
        cursor = (
            self.collection.find(query)
            .sort([(sort_by, sort_dir), ("_id", -1)])
            .skip((page - 1) * page_size)
            .limit(page_size)
        )
        return [serialise(d) async for d in cursor], total

    async def all_matching(
        self, query: dict[str, Any] | None = None, limit: int = 10_000
    ) -> list[dict[str, Any]]:
        """Unpaginated fetch for exports and heatmap aggregation."""
        cursor = self.collection.find(query or {}).sort("detected_at", -1).limit(limit)
        return [serialise(d) async for d in cursor]

    async def count(self, query: dict[str, Any] | None = None) -> int:
        return await self.collection.count_documents(query or {})

    async def near(
        self, latitude: float, longitude: float, radius_m: float = 100.0, limit: int = 20
    ) -> list[dict[str, Any]]:
        """Defects within ``radius_m`` of a point.

        Uses the 2dsphere index where available and falls back to a bounding
        box + haversine filter when it is not (mongomock has no $near).
        """
        try:
            cursor = self.collection.find(
                {
                    "location_geo": {
                        "$near": {
                            "$geometry": {
                                "type": "Point",
                                "coordinates": [longitude, latitude],
                            },
                            "$maxDistance": radius_m,
                        }
                    }
                }
            ).limit(limit)
            return [serialise(d) async for d in cursor]
        except Exception:
            delta = radius_m / 111_320.0
            candidates = await self.all_matching(
                {
                    "location.latitude": {"$gte": latitude - delta, "$lte": latitude + delta},
                    "location.longitude": {
                        "$gte": longitude - delta * 2,
                        "$lte": longitude + delta * 2,
                    },
                },
                limit=500,
            )
            scored = [
                (d, _haversine_m(latitude, longitude, d["location"]["latitude"], d["location"]["longitude"]))
                for d in candidates
            ]
            return [d for d, dist in sorted(scored, key=lambda p: p[1]) if dist <= radius_m][:limit]

    # ----------------------------------------------------------- analytics

    async def analytics(
        self, query: dict[str, Any] | None = None, days: int = 30
    ) -> dict[str, Any]:
        """Aggregate counts backing the dashboard's analytics panel.

        Computed in Python over the filtered set rather than as a Mongo
        aggregation pipeline, because the same code path must work against the
        in-memory fallback (mongomock's ``$group`` support is partial). At
        dashboard scale - thousands of defects, not millions - the difference
        is not measurable; the docstring in docs/ARCHITECTURE.md notes the
        aggregation-pipeline rewrite as the scaling path.
        """
        documents = await self.all_matching(query, limit=50_000)

        by_severity: dict[str, int] = defaultdict(int)
        by_status: dict[str, int] = defaultdict(int)
        by_class: dict[str, int] = defaultdict(int)
        by_day: dict[str, dict[str, int]] = defaultdict(lambda: {"count": 0, "severe": 0})

        cutoff = _utc_now() - timedelta(days=days)
        priorities: list[float] = []

        for doc in documents:
            by_severity[doc["severity"]] += 1
            by_status[doc["status"]] += 1
            by_class[doc["defect_class"]] += 1
            priorities.append(float(doc.get("priority_score", 0.0)))

            detected = _as_aware(doc.get("detected_at"))
            if isinstance(detected, datetime) and detected >= cutoff:
                key = detected.date().isoformat()
                by_day[key]["count"] += 1
                if doc["severity"] == "Severe":
                    by_day[key]["severe"] += 1

        open_defects = sum(by_status.get(s, 0) for s in OPEN_STATUSES)
        severe_open = sum(
            1
            for d in documents
            if d["severity"] == "Severe" and d["status"] in OPEN_STATUSES
        )
        top_priority = sorted(
            (d for d in documents if d["status"] in OPEN_STATUSES),
            key=lambda d: d.get("priority_score", 0.0),
            reverse=True,
        )[:10]

        return {
            "total_defects": len(documents),
            "open_defects": open_defects,
            "repaired_defects": by_status.get("Repaired", 0),
            "severe_open": severe_open,
            "mean_priority": round(sum(priorities) / len(priorities), 2) if priorities else 0.0,
            "by_severity": [
                {"severity": s, "count": by_severity.get(s, 0)}
                for s in ("Minor", "Moderate", "Severe")
            ],
            "by_status": [
                {"status": s, "count": by_status.get(s, 0)}
                for s in ("New", "Verified", "Scheduled", "Repaired", "Rejected")
            ],
            "by_class": [
                {"defect_class": c, "count": by_class.get(c, 0)}
                for c in ("pothole", "crack", "manhole")
                if by_class.get(c, 0) or c != "manhole"
            ],
            "over_time": [
                {"date": day, "count": v["count"], "severe": v["severe"]}
                for day, v in sorted(by_day.items())
            ],
            "top_priority": top_priority,
            "generated_at": _utc_now(),
        }

    async def heatmap(
        self, query: dict[str, Any] | None = None, cell_size_deg: float = 0.002
    ) -> dict[str, Any]:
        """Road-health heatmap: defect density weighted by severity.

        Snaps every defect to a fixed lat/lon grid (~200 m at
        ``cell_size_deg=0.002``) and scores each cell by a severity-weighted
        count, so a cell with three Severe potholes outranks one with three
        Minor cracks rather than tying with it.
        """
        documents = await self.all_matching(query, limit=50_000)
        weights = {"Minor": 1.0, "Moderate": 2.0, "Severe": 4.0}
        cells: dict[tuple[float, float], dict[str, Any]] = {}

        for doc in documents:
            location = doc.get("location") or {}
            lat, lon = location.get("latitude"), location.get("longitude")
            if lat is None or lon is None:
                continue
            key = (
                round(math.floor(lat / cell_size_deg) * cell_size_deg, 6),
                round(math.floor(lon / cell_size_deg) * cell_size_deg, 6),
            )
            cell = cells.setdefault(
                key,
                {"count": 0, "severe_count": 0, "weight": 0.0, "priority_sum": 0.0},
            )
            cell["count"] += 1
            cell["weight"] += weights.get(doc["severity"], 1.0)
            cell["priority_sum"] += float(doc.get("priority_score", 0.0))
            if doc["severity"] == "Severe":
                cell["severe_count"] += 1

        max_weight = max((c["weight"] for c in cells.values()), default=1.0) or 1.0
        result = [
            {
                # Report the cell centre so pins sit mid-cell, not on a corner.
                "latitude": round(lat + cell_size_deg / 2, 6),
                "longitude": round(lon + cell_size_deg / 2, 6),
                "count": cell["count"],
                "severe_count": cell["severe_count"],
                "mean_priority": round(cell["priority_sum"] / cell["count"], 2),
                "intensity": round(cell["weight"] / max_weight, 4),
            }
            for (lat, lon), cell in cells.items()
        ]
        result.sort(key=lambda c: c["intensity"], reverse=True)
        return {
            "cells": result,
            "cell_size_deg": cell_size_deg,
            "max_count": max((c["count"] for c in result), default=0),
        }

    # ------------------------------------------------- stage 8: retraining

    async def export_for_retraining(
        self, include_rejected: bool = True, limit: int = 50_000
    ) -> list[dict[str, Any]]:
        """Human-reviewed detections, which is what stage 8 trains on.

        * ``Verified`` / ``Scheduled`` / ``Repaired`` -> confirmed true positives
        * ``Rejected`` -> confirmed false positives (hard negatives)
        * ``review_label`` set -> a corrected class label

        Untouched ``New`` rows are excluded: they carry no human signal, and
        training on the model's own unreviewed output would just amplify its
        existing bias.
        """
        statuses = ["Verified", "Scheduled", "Repaired"]
        if include_rejected:
            statuses.append("Rejected")
        return await self.all_matching({"status": {"$in": statuses}}, limit=limit)

    # ---------------------------------------------------------------- jobs

    async def save_job(self, job: dict[str, Any]) -> dict[str, Any]:
        await self.jobs.update_one(
            {"job_id": job["job_id"]}, {"$set": job}, upsert=True
        )
        return job

    async def get_job(self, job_id: str) -> dict[str, Any] | None:
        document = await self.jobs.find_one({"job_id": job_id})
        if not document:
            return None
        document.pop("_id", None)
        for key in ("created_at", "started_at", "finished_at"):
            if key in document:
                document[key] = _as_aware(document[key])
        return document

    async def list_jobs(self, limit: int = 20) -> list[dict[str, Any]]:
        cursor = self.jobs.find({}).sort("created_at", -1).limit(limit)
        jobs = []
        async for document in cursor:
            document.pop("_id", None)
            for key in ("created_at", "started_at", "finished_at"):
                if key in document:
                    document[key] = _as_aware(document[key])
            jobs.append(document)
        return jobs


def _oid(value: str) -> Any:
    """Accept either an ObjectId hex string or a plain string _id."""
    from bson import ObjectId

    try:
        return ObjectId(value)
    except Exception:
        return value


def _haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    radius = 6_371_000.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = p2 - p1
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * radius * math.asin(math.sqrt(a))
